### ISSUE TITLE
use_username_as_clientid does not work

### ISSUE THREAD

**Issue by MalteJ** [emqx/emqx#2529]
use_username_as_clientid doesn't work on my installation (Debian 9 with emqx v3.1.0) as expected.
I have set

    zone.external.use_username_as_clientid = true
    zone.internal.use_username_as_clientid = true

I do authentication via TLS certificates

    listener.ssl.external.peer_cert_as_username = cn

When I do `emqx_ctl clients list` I see the correct usernames but the clientid still stays the clientid, that the client is providing. I want the clientid and username to be the certificates CN!
Otherwise the clients can disconnect other devices by sending a clientid owned by a different device.

**Comment by MalteJ** [comment]
@tigercl maybe you can help? :)

**Comment by MalteJ** [comment]
Well, actually it looks like it does work - but in a wrong way:
The client provided clientid is discarded - which is correct.
But the new clientid is the username that the client is providing and not the certificate CN.

So the clients turn up as follows:
clientid is the provided username
username is the certificate CN

It should be:
clientid is certificate CN
username is certificate CN

**Comment by HJianBo** [comment]
Hi, @MalteJ We have released this feature in the v3.1.1.

Close it first. Plz reopen it if has any question there.

**Comment by asierg95** [comment]
Hi, @HJianBo I have tried Emqx v3.1.2, and the bug persist. I use the cert as username, and I enabled: `zone.external.use_username_as_clientid = true
zone.internal.use_username_as_clientid = true`
But it uses the clientId I give in MQTT.fx, it don't use the user as clientId

**Comment by asierg95** [comment]
Hi, @HJianBo I just openned a new issue, with the version 3.1.1 using CentOS7, with certificates it doesn't work.  https://github.com/emqx/emqx/issues/2618

**Comment by ifuidio** [comment]
Hi, @HJianBo , same problem is with emqx 4.0.3, if using TLS + use_username_as_clientid does not work
