### ISSUE TITLE
function_clause when subscribe topic

### ISSUE THREAD

**Issue by frlzk** [emqx/emqx#2679]
#### Environment

- OS: ubuntu18
- Erlang/OTP:  21
- EMQ: 3.2

#### Description
When client subscribe topic has follow error: 

2019-07-09 15:56:50.283 [error] 7f0000018e905d2447f7 ** Generic server <0.18457.4> terminating 
** Last message in was {'$gen_cast',
                        {subscribe,<0.18455.4>,
                         {1,undefined,
                          [{<<"/world">>,
                            #{nl => 0,qos => 1,rap => 0,rc => 1,rh => 0}}|
                           {ok,[]}]}}}
** When Server state == {state,internal,15000,true,
                               #Fun<emqx_session.1.109586832>,
                               <<"7f0000018e905d2447f7">>,<<"admin">>,
                               <0.18455.4>,undefined,1,#{},
                               {emqx_inflight,32,{0,nil}},
                               undefined,
                               {mqueue,true,1000,0,0,none,0,{queue,[],[],0}},
                               #{},undefined,0,undefined,undefined,
                               {emqx_gc,#{}},
                               {1562,659010,280794},
                               undefined,undefined}
** Reason for termination == 
** {function_clause,
       [{lists,foldr,
            [#Fun<emqx_session.11.109586832>,{[],#{}},{ok,[]}],
            [{file,"lists.erl"},{line,1275}]},
        {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
        {emqx_session,handle_cast,2,
            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_session.erl"},
             {line,468}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}

**Comment by Gilbert-Wong** [comment]
Hi, @frlzk, thanks for your feedback, could you please tell me how do you subscribe to the topic, which mqtt client do you use? It will helps me fix this bug.

**Comment by frlzk** [comment]
`
import org.eclipse.paho.client.mqttv3.IMqttActionListener;
import org.eclipse.paho.client.mqttv3.IMqttDeliveryToken;
import org.eclipse.paho.client.mqttv3.IMqttMessageListener;
import org.eclipse.paho.client.mqttv3.IMqttToken;
import org.eclipse.paho.client.mqttv3.MqttAsyncClient;
import org.eclipse.paho.client.mqttv3.MqttCallback;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.MqttMessage;

public class T1 {

	public static void main(String[] args) throws InterruptedException {
		MqttAsyncClient asyncClient=null;
		MqttConnectOptions options = new MqttConnectOptions();
		options.setCleanSession(false);
		options.setUserName("admin");
		options.setPassword("public".toCharArray());
		options.setConnectionTimeout(1000);
		options.setKeepAliveInterval(20);
		options.setAutomaticReconnect(true);
		options.setMqttVersion(3);
		options.setCleanSession(false);
		try {
			asyncClient=new MqttAsyncClient("tcp://127.0.0.1:11883","aaaaaaaa2");
			//asyncClient.setManualAcks(true);
			MqttCallback callback=new MqttCallback() {

				@Override
				public void connectionLost(Throwable e) {
					System.out.println("connectionLost");
					e.printStackTrace();
				}

				@Override
				public void deliveryComplete(IMqttDeliveryToken arg0) {
					System.out.println("deliveryComplete");
				}

				@Override
				public void messageArrived(String arg0, MqttMessage arg1) throws Exception {
					System.out.println("messageArrived");
				}
				
			};
			asyncClient.setCallback(callback);
			// 连接
			IMqttToken token = asyncClient.connect(options,null,new IMqttActionListener() {
				@Override
				public void onFailure(IMqttToken arg0, Throwable e) {
					System.out.println("onFailure");
					e.printStackTrace();
				}
				@Override
				public void onSuccess(IMqttToken t) {
					System.out.println("onSuccess");
					IMqttMessageListener messageListener=new IMqttMessageListener() {
						@Override
						public void messageArrived(String arg0, MqttMessage arg1) throws Exception {
							System.out.println("rrrrrrrr "+arg1.getPayload());
						}
					};
					try {
						//This
						t.getClient().subscribe("/world", 1, messageListener);
					} catch (MqttException e) {
						e.printStackTrace();
					}
				}});
			token.waitForCompletion(30*1000);
			if(token.getException()!=null)
				throw token.getException();
			System.out.println("Success connect to  Mqtt URL: {}" );
		} catch (MqttException e) {
			System.out.println("异常信息为：{}"+e.getMessage());
			throw new IllegalArgumentException(e);
		}
		
		Thread.currentThread().sleep(10000);
	}

}
`

**Comment by Gilbert-Wong** [comment]
Hi, @frlzk, I have tried your code with the latest emqx which is built on develop branch, there is no problem you issued. Here is the screenshot:

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/20479699/60878308-11326e80-a272-11e9-9d15-8d1efa7e2f18.png">

I ran the code you give me:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/20479699/60878386-34f5b480-a272-11e9-9751-b5e5c3fa3453.png">

**Comment by frlzk** [comment]
I use download from  www.emqx.io  emqx-ubuntu18.04-v3.2-rc.3.zip,
just uncompress ,no any change , then run and test 

2019-07-09 18:17:22.109 [error] aaaaaaaa2 ** Generic server <0.1765.0> terminating 
** Last message in was {'$gen_cast',
                        {subscribe,<0.1781.0>,
                         {1,undefined,
                          [{<<"/world">>,
                            #{nl => 0,qos => 1,rap => 0,rc => 1,rh => 0}}|
                           {ok,[]}]}}}
** When Server state == {state,internal,15000,false, 
                               #Fun<emqx_session.1.109586832>,<<"aaaaaaaa2">>,
                               <<"admin">>,<0.1781.0>,undefined,1,#{},
                               {emqx_inflight,32,{0,nil}},
                               undefined,
                               {mqueue,true,1000,0,0,none,0,{queue,[],[],0}},
                               #{},undefined,7200,undefined,
                               #Ref<0.3988215111.2053373953.153851>,
                               {emqx_gc,#{}},
                               {1562,667421,253583},
                               undefined,undefined}
** Reason for termination == 
** {function_clause,
       [{lists,foldr,
            [#Fun<emqx_session.11.109586832>,{[],#{}},{ok,[]}],
            [{file,"lists.erl"},{line,1275}]},
        {lists,foldr,3,[{file,"lists.erl"},{line,1276}]},
        {emqx_session,handle_cast,2,
            [{file,"/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_session.erl"},
             {line,468}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},
        {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-07-09 18:17:22.109 [warning] [Alarm Handler] New Alarm: supervisor_report, Alarm Info: [{supervisor,
                                                            'esockd_connection_sup - <0.1647.0>'},
                                                           {errorContext,
                                                            connection_crashed},
                                                           {reason,
                                                            {function_clause,
                                                             [{lists,foldr,
                                                               [#Fun<emqx_session.11.109586832>,
                                                                {[],#{}},
                                                                {ok,[]}],
                                                               [{file,
                                                                 "lists.erl"},
                                                                {line,1275}]},
                                                              {lists,foldr,3,
                                                               [{file,
                                                                 "lists.erl"},
                                                                {line,1276}]},
                                                              {emqx_session,
                                                               handle_cast,2,
                                                               [{file,
                                                                 "/emqx_temp/emqx_rel/_checkouts/emqx/src/emqx_session.erl"},
                                                                {line,468}]},
                                                              {gen_server,
                                                               try_dispatch,4,
                                                               [{file,
                                                                 "gen_server.erl"},
                                                                {line,637}]},
                                                              {gen_server,
                                                               handle_msg,6,
                                                               [{file,
                                                                 "gen_server.erl"},
                                                                {line,711}]},
                                                              {proc_lib,
                                                               wake_up,3,
                                                               [{file,
                                                                 "proc_lib.erl"},
                                                                {line,
                                                                 259}]}]}}]

**Comment by Gilbert-Wong** [comment]
Thanks for your feedback, @frlzk, I test this code with 1883 port yesterday and it has no problem. Today I test it with 11883, and I reproduce it successfully. I will fix it as soon as possible.

**Comment by frlzk** [comment]
Use same mqtt client , emqx-ubuntu18.04-v3.1.2.zip  is ok.

**Comment by Gilbert-Wong** [comment]
It has been fixed. Here is pull request https://github.com/emqx/emqx/pull/2683

**Comment by frlzk** [comment]
I download emqx_protocol.erl into master souce and compile ,then put beam to 3.2 release ,the problem still exists.

**Comment by Gilbert-Wong** [comment]
Here is my test result:
<img width="1883" alt="image" src="https://user-images.githubusercontent.com/20479699/60946570-24e8de00-a321-11e9-955d-c18ea3b7ba0f.png">

It should be ok if you build emqx correctly.

**Comment by Gilbert-Wong** [comment]
─➤ md5sum emqx_protocol.beam                                                      
15803dc9239a7b3d42604ae0fef39f06  emqx_protocol.beam

**Comment by Gilbert-Wong** [comment]
Hi, @frlzk, how do you build your emqx locally? 

Here is my test result:
<img width="1965" alt="image" src="https://user-images.githubusercontent.com/20479699/60946404-b99f0c00-a320-11e9-8614-49e15bd5cc84.png">

**Comment by frlzk** [comment]
One bin directory uncompress from emqx-ubuntu18.04-v3.2-rc.3.zip.
Other source directory uncompress from emqx-master.
Download emqx_protocol.erl overwrite emqx-master.
Into emqx-master directory and run make.
Copy emqx_protocol.beam to bin emqx3.2/lib/emqx-3.2-rc.3/ebin then run.

**Comment by Gilbert-Wong** [comment]
First, you should make sure that the beam file is replaced correctly or the emqx_protocol.erl you downloaded is correctly.

Second, if your problem is still not been resolved. I suggest you contact me via im tools , such as WeChat or telegram.

My WeChat id is Gilbert--Wong, My telegram id is gilbertwong0096

On Jul 10, 2019, at 4:56 PM, frlzk <notifications@github.com<mailto:notifications@github.com>> wrote:


One bin directory uncompress from emqx-ubuntu18.04-v3.2-rc.3.zip.
Other source directory uncompress from emqx-master.
Download emqx_protocol.erl overwrite emqx-master.
Into emqx-master directory and run make.
Copy emqx_protocol.beam to bin emqx3.2/lib/emqx-3.2-rc.3/ebin then run.

**Comment by frlzk** [comment]
**It's OK**
