### ISSUE TITLE
Emqx_auth_mysql loaded successfully but without acl rules

### ISSUE THREAD

**Issue by chcmq** [emqx/emqx#3057]
#### Environment

- OS: 
- Erlang/OTP: 
- EMQ: 

#### Description

*A description of the issue*

Emqx_auth_mysql loads successfully but without acl rules, just user login authentication

**Comment by tigercl** [comment]
@chcmq Sorry, I don't understand what you mean, could you describe it in more detail?

**Comment by williamfjm** [comment]
Hello i have same issue ,i can load mysql plugin and users load from db but rules created in mqtt_acl  dont work i tried many ways without success .

Erlang/OTP 22
EMQ X Broker 4.0-rc.3
on centos 7
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for Linux (x86_64) 

in config files
allow_anonymous = false
acl_nomatch = deny
acl_file = etc/acl.conf
enable_acl_cache = on
acl_deny_action = ignore

in etc/acl.conf

{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.


{allow, {user, "testu"}, pubsub, ["T1"]}.

{deny, all}.

in emqx_auth_mysql.conf
auth.mysql.acl_query = select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'

and mqtt database


id | allow | ipaddr | username | clientid | access | topic
|11| 1       | NULL   | testu        | NULL    | 2         | mitopic

user testu can suscribe to topic T1 but not to mitopic. 

i tryed many ways witout success .can you help me ?

thanks

**Comment by cesc1802** [comment]
i have same issue and i also config same above. anyone can help me ? very thanks

**Comment by williamfjm** [comment]
hello cesc1802 i fixed the issue ..and is very dumb in my case .I hope your case is the same .
when i fill data-base  with this
 id | allow | ipaddr | username | clientid | access | topic
|11| 1       | NULL   | testu         | NULL    | 3         | mitopic . 
table show in column ipaddr and  clientid the word NULL  ,then dont work ,if these fields are not used 
 id | allow | ipaddr | username | clientid | access | topic
|11| 1       |             | testu         |             | 3         | mitopic 
i hope this help you.

**Comment by cesc1802** [comment]
hi williamfjm, thanks for reply, i will try it now and feed back as soon

**Comment by Fsenxu** [comment]
> hello cesc1802 i fixed the issue ..and is very dumb in my case .I hope your case is the same .
> when i fill data-base with this
> id | allow | ipaddr | username | clientid | access | topic
> |11| 1 | NULL | testu | NULL | 3 | mitopic .
> table shows in column ipaddr and clientid the word NULL ,then dont work ,if these fields are not used they must go empty.
> id | allow | ipaddr | username | clientid | access | topic
> |11| 1 | | testu | | 3 | mitopic
> i hope this help you.

I had set ipaddr = '' but it still not work, please tell me how to make them empty

**Comment by williamfjm** [comment]
It should work with this, can you put a sql statement? or maybe another rule in text settings will block sql rule.

**Comment by muhun** [comment]
issue is with with line 
{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
 if you run broker and your app on same machine , it simply allows all acl to any topic 
just change it to 
**{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#"]}.**

**Comment by brunohorta82** [comment]
I Have the same issue, anyone already solved?

**Comment by zmstone** [comment]
Hi. @brunohorta82 which EMQ X version is it in your case ?

**Comment by brunohorta82** [comment]
> Hi. @brunohorta82 which EMQ X version is it in your case ?

4.2.8

**Comment by zmstone** [comment]
@brunohorta82 could you export some of the sample rows in csv format ?

**Comment by brunohorta82** [comment]
> @brunohorta82 could you export some of the sample rows in csv format ?

Sure:
My acl.conf

{allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.

{allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.

{deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.

{deny, all}.

and mqtt_acl table

id,allow,"ipaddr","username","clientid",access,"topic"
2,1,NULL,NULL,NULL,1,"/smarthome/%c/temperature"

**Comment by jovdipp** [comment]
Hi @brunohorta82 
Thanks for the info, I'm looking into this.

**Comment by k32** [comment]
Sorry, it took my a long time to start looking into this issue. Looking at the rule dump and the SQL query from https://github.com/emqx/emqx/issues/3057#issuecomment-797027387 I think the SQL query will never match.

I think the rule should be configured like this instead:

```
INSERT INTO mqtt_acl (allow, ipaddr, username, clientid, access, topic) VALUES (1, NULL, $all, NULL, 1, '/smarthome/%c/temperature');
```

Notice that username is `'$all'` instead of NULL. I will update `emqx-docs` with the correct command.
