### ISSUE TITLE
Mnesia emqx_acl only has a single disc copy

### ISSUE THREAD

**Issue by umeat** [emqx/emqx#4395]
I have a cluster with three nodes (running in Kubernetes). I'm using the Mnesia ACL plugin for authorization of requests and noticed that the other nodes cannot authorize requests while the emqx-0 node reboots. This results in the complete inability for emqx-1 and emqx-2 to send / receive any messages while emqx-0 is down.

Running `emqx_ctl mnesia` on emqx-0 shows that emqx_acl is only mentioned as having a disc copy on the node emqx-0. I don't fully understand the output here, but it looks like this is why the other nodes are unable to check_acl while emqx-0 is down.

Is there a way to have this replicated across all nodes? Nothing about this is mentioned in the documentation I can find.

The output of emqx_ctl mnesia is here:

```
/opt/emqx $ emqx_ctl mnesia
===> System info in version "4.16.3", debug level = none <===
opt_disc. Directory "/opt/emqx/data/mnesia/emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local" is used.
use fallback at restart = false
running db nodes   = ['emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local']
stopped db nodes   = [] 
master node tables = []
remote             = []
ram_copies         = [emqx_channel_registry,emqx_resource_type,emqx_retainer,
                      emqx_route,emqx_routing_node,emqx_rule_action,
                      emqx_shared_subscription,emqx_trie,emqx_trie_node]
disc_copies        = [emqx_acl,emqx_alarm,emqx_alarm_history,emqx_banned,
                      emqx_resource,emqx_rule,emqx_user,mqtt_admin,mqtt_app,
                      schema]
disc_only_copies   = []
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_alarm,
                                                                             emqx_alarm_history,
                                                                             emqx_acl]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_user,
                                                                             mqtt_app,
                                                                             schema]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [mqtt_admin,
                                                                            emqx_banned,
                                                                            emqx_rule,
                                                                            emqx_resource]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [emqx_resource_type,
                                                                            emqx_routing_node,
                                                                            emqx_channel_registry,
                                                                            emqx_retainer,
                                                                            emqx_route,
                                                                            emqx_trie_node,
                                                                            emqx_rule_action,
                                                                            emqx_trie,
                                                                            emqx_shared_subscription]
156 transactions committed, 23 aborted, 2 restarted, 22 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
```

**Comment by umeat** [comment]
In case it's relevant, here's the output from emqx-1:

```
===> System info in version "4.16.3", debug level = none <===
opt_disc. Directory "/opt/emqx/data/mnesia/emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local" is used.
use fallback at restart = false
running db nodes   = ['emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local']
stopped db nodes   = [] 
master node tables = []
remote             = [emqx_acl]
ram_copies         = [emqx_alarm,emqx_alarm_history,emqx_banned,
                      emqx_channel_registry,emqx_resource,emqx_resource_type,
                      emqx_retainer,emqx_route,emqx_routing_node,emqx_rule,
                      emqx_rule_action,emqx_shared_subscription,emqx_trie,
                      emqx_trie_node,mqtt_admin]
disc_copies        = [emqx_user,mqtt_app,schema]
disc_only_copies   = []
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_acl]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_user,
                                                                             mqtt_app,
                                                                             schema]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [mqtt_admin,
                                                                            emqx_banned,
                                                                            emqx_rule,
                                                                            emqx_resource]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [emqx_resource_type,
                                                                            emqx_routing_node,
                                                                            emqx_channel_registry,
                                                                            emqx_retainer,
                                                                            emqx_route,
                                                                            emqx_trie_node,
                                                                            emqx_rule_action,
                                                                            emqx_trie,
                                                                            emqx_shared_subscription]
[{'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [emqx_alarm,
                                                                            emqx_alarm_history]
251 transactions committed, 27 aborted, 12 restarted, 6 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
```

And from emqx-2:

```
===> System info in version "4.16.3", debug level = none <===
opt_disc. Directory "/opt/emqx/data/mnesia/emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local" is used.
use fallback at restart = false
running db nodes   = ['emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local','emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local']
stopped db nodes   = [] 
master node tables = []
remote             = [emqx_acl]
ram_copies         = [emqx_alarm,emqx_alarm_history,emqx_banned,
                      emqx_channel_registry,emqx_resource,emqx_resource_type,
                      emqx_retainer,emqx_route,emqx_routing_node,emqx_rule,
                      emqx_rule_action,emqx_shared_subscription,emqx_trie,
                      emqx_trie_node,mqtt_admin]
disc_copies        = [emqx_user,mqtt_app,schema]
disc_only_copies   = []
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_acl]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',disc_copies}] = [emqx_user,
                                                                             mqtt_app,
                                                                             schema]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',disc_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [mqtt_admin,
                                                                            emqx_banned,
                                                                            emqx_rule,
                                                                            emqx_resource]
[{'emqx@emqx-0.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-1.emqx-headless.gnss-stream.svc.cluster.local',ram_copies},
 {'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [emqx_resource_type,
                                                                            emqx_routing_node,
                                                                            emqx_channel_registry,
                                                                            emqx_retainer,
                                                                            emqx_route,
                                                                            emqx_trie_node,
                                                                            emqx_rule_action,
                                                                            emqx_trie,
                                                                            emqx_shared_subscription]
[{'emqx@emqx-2.emqx-headless.gnss-stream.svc.cluster.local',ram_copies}] = [emqx_alarm,
                                                                            emqx_alarm_history]
227 transactions committed, 31 aborted, 23 restarted, 9 logged to disc
0 held locks, 0 in queue; 0 local transactions, 0 remote
0 transactions waits for other nodes: []
```

**Comment by k32** [comment]
Hello,
I am very new to the project, so apologies in advance. 
Could you show output of `emqx_ctl plugins list` on each node? I think `emqx_acl` table is replicated to all nodes that have `emqx_auth_mnesia` plugin enabled.

**Comment by umeat** [comment]
Sure thing. They all have the `emqx_auth_mnesia` plugin enabled.

emqx-0:
```
Plugin(emqx_auth_clientid, description=EMQ X Authentication with ClientId/Password, active=false)
Plugin(emqx_auth_http, description=EMQ X Authentication/ACL with HTTP API, active=true)
Plugin(emqx_auth_jwt, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mnesia, description=EMQ X Authentication with Mnesia, active=true)
Plugin(emqx_auth_mongo, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, description=EMQ X Authentication/ACL with MySQL, active=false)
Plugin(emqx_auth_pgsql, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_auth_username, description=EMQ X Authentication with Username and Password, active=false)
Plugin(emqx_bridge_mqtt, description=EMQ X Bridge to MQTT Broker, active=false)
Plugin(emqx_coap, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_extension_hook, description=EMQ X Extension for Hook, active=false)
Plugin(emqx_lua_hook, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_plugin_template, description=EMQ X Plugin Template, active=false)
Plugin(emqx_psk_file, description=EMQX PSK Plugin from File, active=false)
Plugin(emqx_recon, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_reloader, description=EMQ X Reloader Plugin, active=false)
Plugin(emqx_retainer, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, description=EMQ X Rule Engine, active=true)
Plugin(emqx_sasl, description=EMQ X SASL, active=false)
Plugin(emqx_sn, description=EMQ X MQTT-SN Plugin, active=false)
Plugin(emqx_statsd, description=Statsd for EMQ X, active=false)
Plugin(emqx_stomp, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_web_hook, description=EMQ X WebHook Plugin, active=false)
```

emqx-1:
```
Plugin(emqx_auth_clientid, description=EMQ X Authentication with ClientId/Password, active=false)
Plugin(emqx_auth_http, description=EMQ X Authentication/ACL with HTTP API, active=true)
Plugin(emqx_auth_jwt, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mnesia, description=EMQ X Authentication with Mnesia, active=true)
Plugin(emqx_auth_mongo, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, description=EMQ X Authentication/ACL with MySQL, active=false)
Plugin(emqx_auth_pgsql, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_auth_username, description=EMQ X Authentication with Username and Password, active=false)
Plugin(emqx_bridge_mqtt, description=EMQ X Bridge to MQTT Broker, active=false)
Plugin(emqx_coap, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_extension_hook, description=EMQ X Extension for Hook, active=false)
Plugin(emqx_lua_hook, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_plugin_template, description=EMQ X Plugin Template, active=false)
Plugin(emqx_psk_file, description=EMQX PSK Plugin from File, active=false)
Plugin(emqx_recon, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_reloader, description=EMQ X Reloader Plugin, active=false)
Plugin(emqx_retainer, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, description=EMQ X Rule Engine, active=true)
Plugin(emqx_sasl, description=EMQ X SASL, active=false)
Plugin(emqx_sn, description=EMQ X MQTT-SN Plugin, active=false)
Plugin(emqx_statsd, description=Statsd for EMQ X, active=false)
Plugin(emqx_stomp, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_web_hook, description=EMQ X WebHook Plugin, active=false)
```

emqx-2:
```
Plugin(emqx_auth_clientid, description=EMQ X Authentication with ClientId/Password, active=false)
Plugin(emqx_auth_http, description=EMQ X Authentication/ACL with HTTP API, active=true)
Plugin(emqx_auth_jwt, description=EMQ X Authentication with JWT, active=false)
Plugin(emqx_auth_ldap, description=EMQ X Authentication/ACL with LDAP, active=false)
Plugin(emqx_auth_mnesia, description=EMQ X Authentication with Mnesia, active=true)
Plugin(emqx_auth_mongo, description=EMQ X Authentication/ACL with MongoDB, active=false)
Plugin(emqx_auth_mysql, description=EMQ X Authentication/ACL with MySQL, active=false)
Plugin(emqx_auth_pgsql, description=EMQ X Authentication/ACL with PostgreSQL, active=false)
Plugin(emqx_auth_redis, description=EMQ X Authentication/ACL with Redis, active=false)
Plugin(emqx_auth_username, description=EMQ X Authentication with Username and Password, active=false)
Plugin(emqx_bridge_mqtt, description=EMQ X Bridge to MQTT Broker, active=false)
Plugin(emqx_coap, description=EMQ X CoAP Gateway, active=false)
Plugin(emqx_dashboard, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_extension_hook, description=EMQ X Extension for Hook, active=false)
Plugin(emqx_lua_hook, description=EMQ X Lua Hooks, active=false)
Plugin(emqx_lwm2m, description=EMQ X LwM2M Gateway, active=false)
Plugin(emqx_management, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_plugin_template, description=EMQ X Plugin Template, active=false)
Plugin(emqx_psk_file, description=EMQX PSK Plugin from File, active=false)
Plugin(emqx_recon, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_reloader, description=EMQ X Reloader Plugin, active=false)
Plugin(emqx_retainer, description=EMQ X Retainer, active=true)
Plugin(emqx_rule_engine, description=EMQ X Rule Engine, active=true)
Plugin(emqx_sasl, description=EMQ X SASL, active=false)
Plugin(emqx_sn, description=EMQ X MQTT-SN Plugin, active=false)
Plugin(emqx_statsd, description=Statsd for EMQ X, active=false)
Plugin(emqx_stomp, description=EMQ X Stomp Protocol Plugin, active=false)
Plugin(emqx_web_hook, description=EMQ X WebHook Plugin, active=false)
```

**Comment by k32** [comment]
Thanks for the info. Which version of EMQX are you using?

**Comment by umeat** [comment]
version 4.1.3

**Comment by k32** [comment]
Thanks, I think this version has a bug where the `emqx_acl` table is not copied. It has been fixed in this commit: `e236196fa61152f9850aeffc49b2b350d9a9ed47`. Let me check which release it was merged to. In any case, I think the fix should be easy enough to backport.

**Comment by umeat** [comment]
I'll try to upgrade and let you know! Thanks.

**Comment by k32** [comment]
The fix will be available in v4.3-rc1, which should be released tomorrow.

**Comment by k32** [comment]
I verified on the v4.3-beta that the problem is fixed. Closing the issue for now. Please feel free to reopen if there are new details.

**Comment by umeat** [comment]
This is likely a different issue, but the docker environment variables don't seem to be loaded into the config files in version 4.3-rc.1.

The EQMX_LOADED_PLUGINS variable works (I can see that the plugins are loaded in the dashbord) - but (for example) `EMQX_AUTH__HTTP__AUTH_REQ__URL=http://some-url:80/auth` and `EMQX_ACL_NOMATCH=deny`, aren't applied in the config files. In 4.1.3 setting those variables correctly set the variables in `etc/plugins/emqx_auth_mnesia.conf` and `etc/emqx.conf` respectively.

**Comment by umeat** [comment]
fwiw I tested in 4.2.8 and the issue is still present there.

**Comment by k32** [comment]
> fwiw I tested in 4.2.8 and the issue is still present there.

Yes, 4.3.0 will be the first open-source release containing the fix.

> This is likely a different issue, but the docker environment variables don't seem to be loaded into the config files in version 4.3-rc.1.

Could you please open a new ticket?

**Comment by zmstone** [comment]
Hi @umeat
There will be a v4.2.9 to have this bug fixed.
It's hard to say when though.

**Comment by zmstone** [comment]
the fix: https://github.com/emqx/emqx-auth-mnesia/pull/55

More context:
Starting from v4.3, enterprise use the exact same code in `src` and `apps/*` as opensource.
This kind of situation will hopefully not happen again.

**Comment by zmstone** [comment]
fixed in 4.2.9
