### ISSUE TITLE
Getting badmatch error while connecting with cluster redis from auth redis

### ISSUE THREAD

**Issue by VaibhavMishra2069** [emqx/emqx#6383]
### Discussed in https://github.com/emqx/emqx/discussions/6382

<div type='discussions-op-text'>

<sup>Originally posted by **VaibhavMishra2069** December  6, 2021</sup>
We are getting badmatch error while connecting with cluster redis from auth redis
Below are the emqx logs:
2021-12-06 15:14:10.690 [error] <<"675656655555555">>@10.12.0.92:9803 [Hooks] Failed to execute {fun emqx_auth_redis:check/3,[#{auth_cmd => "HMGET mqtt_user:%u password salt",hash_type => {salt,sha256},pool => emqx_auth_redis,super_cmd => undefined,timeout => infinity,type => cluster}]}: {{timeout,{gen_server,call,[<0.1672.0>,{reload_slots_map,1407}]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,215}]},{eredis_cluster,handle_transaction_result,3,[{file,"eredis_cluster.erl"},{line,129}]},{eredis_cluster,query,4,[{file,"eredis_cluster.erl"},{line,119}]},{emqx_auth_redis,check,3,[{file,"emqx_auth_redis.erl"},{line,40}]},{emqx_hooks,safe_execute,2,[{file,"emqx_hooks.erl"},{line,164}]},{emqx_hooks,do_run_fold,3,[{file,"emqx_hooks.erl"},{line,143}]},{emqx_access_control,authenticate,1,[{file,"emqx_access_control.erl"},{line,77}]},{emqx_channel,auth_connect,2,[{file,"emqx_channel.erl"},{line,1181}]}]}

2021-12-06 15:14:10.717 [error] ** Generic server <0.5864.16> terminating 
** Last message in was {'EXIT',<0.5863.16>,
                        {{badmatch,
                          {error,
                           {undef,
                            [{erlang,send_after,
                              [100,<0.5865.16>,reconnect,5000,
                               [{ssl_options,
                                 [{cacertfile,
                                   "/opt/emqx/etc/certs/MyRootCA.pem"},
                                  {certfile,"/opt/emqx/etc/certs/MyEMQ1.pem"},
                                  {keyfile,
                                   "/opt/emqx/etc/certs/MyEMQ1.key"}]}]],
                              []},
                             {eredis_cluster_pool_worker,start_connection,5,
                              [{file,"eredis_cluster_pool_worker.erl"},
                               {line,92}]},
                             {eredis_cluster_pool_worker,init,1,
                              [{file,"eredis_cluster_pool_worker.erl"},
                               {line,35}]},
                             {gen_server,init_it,2,
                              [{file,"gen_server.erl"},{line,374}]},
                             {gen_server,init_it,6,
                              [{file,"gen_server.erl"},{line,342}]},
                             {proc_lib,init_p_do_apply,3,
                              [{file,"proc_lib.erl"},{line,249}]}]}}},
                         [{poolboy,new_worker,1,
                           [{file,"poolboy.erl"},{line,275}]},
                          {poolboy,prepopulate,3,
                           [{file,"poolboy.erl"},{line,296}]},
                          {poolboy,init,3,[{file,"poolboy.erl"},{line,145}]},
                          {gen_server,init_it,2,
                           [{file,"gen_server.erl"},{line,374}]},
                          {gen_server,init_it,6,
                           [{file,"gen_server.erl"},{line,342}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,249}]}]}}

We just changed the auth.redis.type = cluster 
in emqx_auth_redis file

**EMQX version: 4.2.5**

**Comment by k32** [comment]
This looks like a legacy problem that has been fixed by this commit:  
https://github.com/emqx/eredis_cluster/commit/11d853b526667caca01e101449f4f7db8d16187a#diff-55f5e5719038a231deb173b99661288f87c6e43fac0d888e9683257a74daf45f

**Comment by k32** [comment]
EMQX 4.2.11 already contains the fix, so update should solve the problem.

**Comment by VaibhavMishra2069** [comment]
Hi @k32 we can't change this version on production. Do we have any solution in this version

**Comment by VaibhavMishra2069** [comment]
Some how its still not working with 4.2.11. Getting same issues.

**Comment by k32** [comment]
The issue you've submitted here actually has a different error message: https://github.com/emqx/emqx-auth-redis/issues/203

**Comment by VaibhavMishra2069** [comment]
@k32      Its a docker image mentioned inside kubernetes stateful set. We are trying connect  with azure cache redis cluster.
In the MyRootCA.pem we have given Baltimore Root Ca 
https://baltimore-cybertrust-root.chain-demos.digicert.com/info/index.html

**Comment by VaibhavMishra2069** [comment]
> 

Yes we tried by giving ssl off also at that we got reachable error. We know it will not connect because on redis broker we have ssl on

**Comment by k32** [comment]
Could you specify the exact tag of the docker image?

**Comment by VaibhavMishra2069** [comment]
@k32  emqx/emqx:4.2.5
And  emqx/emqx:4.2.11

**Comment by VaibhavMishra2069** [comment]
Hi @k32 can you please look into it more.

**Comment by k32** [comment]
Would you mind helping to test the following patch:
[patch.tar.gz](https://github.com/emqx/emqx/files/7684261/patch.tar.gz)
It contains a fixed version of the file causing the problem. Unpack it and run `docker build`, then use the resulting container. Disclaimer: I didn't test it thoroughly.
